### ISSUE TITLE
Sorry to bother, has your erigon worked normally?

### ISSUE THREAD

**Issue by suxnju** [jiOnederfull/onederfull-docker#1]
Sorry to propose an unrelated issue in this repository. In fact, I tried to send you a message through discord, but failed. Is it convenient to add me as a friend (my id is Skyy)?

Indeed, I encountered some problems similar with yours mentioned before in [erigon discord](https://discord.com/channels/687972960811745322/897877410131902464/1184530806350303263) and have you solved your problems and how to solve?

**Comment by jiOnederfull** [comment]
Hi @suxnju, I also failed to add you as a friend.

I just restarted several times and waited then it worked.

Hope it also works for you too.

And any further question, please add @onederfull_0v0 on telegram. If you checked, please let me know so that I could erase my telegram handle.

Thank you!

**Comment by suxnju** [comment]
Thanks a lot!
